#!/bin/bash

RIG_NUMBER="1"

ETC_ADDRESS="YOUR_ETC_ADDRESS_HERE"

FAN_SPEED=50

#######################################################################################
IPW=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
IP_AS_WORKER=$(echo -n $IPW | tail -c -3 | sed 'y/./0/')
MAC=$(ifconfig -a | grep -Po 'HWaddr \K.*$')
MAC_AS_WORKER=$(echo -n $MAC | tail -c -4 | sed 's|[:,]||g')
sleep 2
WORKERNAME=$RIG_NUMBER'__'$MAC_AS_WORKER'__'$IP_AS_WORKER
CORE_OVERCLOCK_LEVEL=7
MEMORY_OVERCLOCK_LEVEL=1
FAN_SP=$(awk "BEGIN {printf \"%.0f\n\", 255 * $FAN_SPEED/100}")
sudo '/home/m1/rocm-smi' -s
sudo '/home/m1/rocm-smi' -r
sudo '/home/m1/rocm-smi' --setperflevel high
sudo '/home/m1/rocm-smi' --setmclk $MEMORY_OVERCLOCK_LEVEL
sudo '/home/m1/rocm-smi' --setsclk $CORE_OVERCLOCK_LEVEL
sudo '/home/m1/rocm-smi' --setfan $FAN_SP -f
CLIENT="/home/m1/eth/10_1/ethdcrminer64 -epool us1-etc.ethermine.org:4444 -ewal $ETC_ADDRESS.$WORKERNAME -epsw x -mode 1 -dbg -1 -wd 0 -mport -3333;"
until $CLIENT
do
crash=$(($crash+1))
if [ $crash == 3 ]
then
sudo reboot
fi
done
fi
